# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e79b2094dc1318e882b48546a448a291aefaea05c4bab78849753c7544e50d2c58fd6c9c2293a0340bbfe50e3f88e62381352ef3e89d3a7369cab7faa2d4af9

test:
  secret_key_base: c3db89b528b90af8d32213e138f962d2275a8fcf0c9dbde8ba0d8345b44c795142f4b168936b7e61a7db6899ea95568a9068ff34052e2799bc792e46be4a7c57

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
