# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7010013ee22a72883e4da0d437d4b9a70c9056a2f441834084b2f4ae4ecf26361112dc0a78d3b77ffb97be9b30bb28298abd961e5167eab7a0835ab87d899f27

test:
  secret_key_base: df06ee96861a0667078071addea7c24f1cf7bc48ab218971f15a523e86843f02f69a774971e49d1814f63bdb102c6aa335fc0228d18a0d627cac7af55b82f9c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
